### ISSUE TITLE
Suggestion about Dwellers editor and Item / receipe search function

### ISSUE THREAD

**Issue by bluesaka111** [robot9706/FSSE#1]
My suggestion for search function:
- Search any item that contain text in the search textbox (Like when i type in "Amplified" then the app will return a list of items that have "Amplified" in its name)
- Search item by type and tier (maybe let user choose it from a drop down list)
- Search remember its last keywork

My suggestion for Dwellers item display: maybe like... this? 
![Dweller info display... suggestion?](https://cloud.githubusercontent.com/assets/14975973/15420655/305002d4-1e98-11e6-8c1d-28adb4d6be89.png)

**Comment by robot9706** [comment]
The recipe view is in a very early stage beacause I didn't have much time to expand it.
Also what is the second thing? (The form design, where should I use that?)

**Comment by bluesaka111** [comment]
That second thing in screenshot below (EditDweller form)
![ddd](https://cloud.githubusercontent.com/assets/14975973/15447148/9e740764-1f61-11e6-91fe-20152cfe9614.png)

Just imagine form border is your phone physic border >.<
Dark button is unclickable

Link demo solution [ https://drive.google.com/file/d/0Bz_u0fNcoYQTVnM0VWhZQlRTeHM/view?usp=sharing ]

**Comment by robot9706** [comment]
That would make the dweller list very long, and if you have 200+ dwellers this list is already long..

**Comment by bluesaka111** [comment]
yeah, but if user can select dweller based on their assigned room / or wandering (no room assigned) then the list wont be that long.

and that dweller info is only shown when you click on Dweller name but i forgot to build it into demo :-1: 
that all, keep up the good work with this app :+1:

**Comment by robot9706** [comment]
Okay anyway, this issue is marked as an "enhancement" so when I'll work on an update I'll take a look at this one too.

**Comment by robot9706** [comment]
I implemented the sorting feature for the dwellers sometime ago. The dropdown idea made the UI very slow also didn't have much room to show the data, so I removed that.

I think I also need to rework the recipe screen.

I'm going to close this.
