### ISSUE TITLE
Create a family tree visualizer

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#10]
To see through the relations of the dwellers.

**Comment by fayescarlet64** [comment]
This will be pretty cool to have in the editor. I made a family tree myself using Notepad, but sometimes I am never sure if I forgot someone or not.

**Comment by sugnaangus** [comment]
Would it be possible to have the ID numbers of the parents of a dweller be included in the CSV?

**Comment by robot9706** [comment]
I think the parents are not known, but maybe it is possible to look it up in some relatives list or something.

https://github.com/robot9706/FSSE/issues/55
