### ISSUE TITLE
Weapons stat edit

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#103]
Is there a way to add or modify the stats of a weapon? I saw a youtube video that shows weapons I never seen in the game with stats like 35 damage.

**Comment by robot9706** [comment]
They are hardcoded into the game. Might be possible with modding.

**Comment by Xanthor** [comment]
I went back to the video, I'm going to post the link to it here as well. The weapons with higher stats was part of last years Halloween promotion. If they added those strange weapons and Halloween costumes with the larger bonuses,   shouldn't they still be in the program where someone can edit them into the game? Even if removed, players still have them.

https://www.youtube.com/watch?v=XqAxCzchRB8&t=324s

**Comment by robot9706** [comment]
If they are still in the game you can find them in the editors.
