### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by PRIC3L3SS** [robot9706/FSSE#105]
I am new to this, when i try to use the "mods" tab it says

"Failed to locate mods folder. Go to settings, setup the game installation paths and try again"

Sorry for being a noob but how do i do this?

**Comment by robot9706** [comment]
Like this:

![how_to](https://cloud.githubusercontent.com/assets/3697447/26282582/47c7a60a-3e14-11e7-9272-edd9323c83eb.PNG)

Then just browse the paths or if you are playing with the Win10 version press the "Discover" button. The Beth.NET version is usually located in something like "C:\Program Files (x86)\Bethesda.net Launcher\games\FalloutShelter".

**Comment by PRIC3L3SS** [comment]
Ok, i did everything and now it is telling me it cant find the mod folder. i waited for the vault to load like the error said to and the mod folder still isn't loading.

**Comment by PRIC3L3SS** [comment]
[
![screenshot_42](https://cloud.githubusercontent.com/assets/28832556/26285203/3d0a3e44-3e19-11e7-9107-97bf6029108d.png)
![screenshot_41](https://cloud.githubusercontent.com/assets/28832556/26285205/4214ca80-3e19-11e7-9bb6-46dd2fb3c3ba.png)

](url)

**Comment by robot9706** [comment]
Are you sure the game is modded? Goto the credits screen and see if it starts with "Modded Fallout Shelter".

**Comment by PRIC3L3SS** [comment]
It does not start with modded fallout shelter

**Comment by robot9706** [comment]
Then obviously it's not modded. Are you sure you placed the modded files to the correct folders? Or maybe Steam detects the changes and fixes the files?

**Comment by PRIC3L3SS** [comment]
I dont think the modded files are in the correct folder

**Comment by PRIC3L3SS** [comment]
How do i check?

**Comment by robot9706** [comment]
You can check it by going to the credits screen as I mentioned before. You can find an installation guide here: http://robot9706.github.io/FSSE/?s=undw
Open the "Steam modded game" title.

**Comment by PRIC3L3SS** [comment]
:DD It is working now, thank you very much for your help.
