### ISSUE TITLE
Ability to do other quests

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#107]
I see there is the ability to remove a completed quest which is great if one gets bugged. But what about the ability to have a quest show up so it can be done?

**Comment by robot9706** [comment]
The available quests list isn't saved into the save file. It is generated runtime based on the quests done. However it might be possible to add a quest as a weekly or dialy quest which makes it appear in the quests list.

**Comment by robot9706** [comment]
I tried changing dialy, weekly and standalone quests but the game does check if it's possible to do the quests and if not it changes back to the original. So it's not really possible to add quests to the list.
