### ISSUE TITLE
Disabling the controller

### ISSUE THREAD

**Issue by Neyami** [robot9706/FSSE#109]
Would it be possible to disable the controller?

I only play with the mouse and keyboard, and when I scroll the screen my controller keeps vibrating. It has even fallen off my couch a few times from this :P

And sometimes the controller sensitivity gets messed up and it takes over, making the game ignore any mouse input.

**Comment by robot9706** [comment]
Just for a quick fix I think you could disable the controller temporary in the Device Manager (if you are on Windows). But yeah if it's not hidden deep in the game, then it's possible. I'll update the mods tomorrow then I'll see what I can do about mod ideas that I collected over time.

**Comment by robot9706** [comment]
Which platform are you playing on? Steam or Beth.NET? I'm asking because I made mod which should disable the controller vibration however I can't test it because my controller doesn't even vibrate with the original version. So I'd like to create a test version that you could try.

**Comment by Neyami** [comment]
I'm on the Steam version

**Comment by robot9706** [comment]
I compiled the test version for Steam, I also included the new config json files too.
In the mods_config.json you can find the "disable_controller_vibration" mod, that's what you are looking for (It's enabled by default). I'm interested if it works or not.

[Modded.zip](https://github.com/robot9706/FSSE/files/1033453/Modded.zip)

**Comment by Neyami** [comment]
Coo, I'll test it :3 
By the way, there's nothing in the data file about it. Shouldn't there be? :o

**Comment by Neyami** [comment]
It works! :D awesome :O
Being able to completely disable the controller would be even better (sometimes my controller gets a mind of it's own ¯\_(ツ)_/¯) but this is sufficient ^^

**Comment by robot9706** [comment]
@Neyami: Under the data file I meant the "mods_config.json", so yeah that was a bit misleading :) But if it works that's nice.
