### ISSUE TITLE
Logged in today and found the mods to no longer be functional

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#111]
I think they did an update today as none of the mods are working.

**Comment by robot9706** [comment]
Yes the game was updated to 1.12 yesterday, but I updated the mods too. Did you update the mods? Make sure to download the latest version from the FSSE website or NexusMods.

**Comment by Xanthor** [comment]
My goof. Didn't play yesterday and get too use to seeing banners blaring update so when I didn't see anything, I posted here. Soon as I went to run the editor it told me there was an update. Trying it out now.
It works fine. At first I used wrong version, but soon as I got message when logging in, knew what I did and fixed it. The two PC versions even though well marked, I still overlooked, again. Thanks for the update.
