### ISSUE TITLE
Updating Android mods, same as full install?

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#112]
I was wondering if upgrading the mods for the android version requires the same steps as in installing from fresh or does the program do it itself?

**Comment by robot9706** [comment]
Unfortunatelly on Android it's the same as installing the mods from a fresh FS. I sign the modded APKs with the same keys so (in theory) you should be able to install it without deleting the older version, but you'd still need to update the game OBBs. So the easiest way is to do a fresh install.
It's possible to download just the game OBB (there are sites for that) but I never tried that way.

**Comment by Xanthor** [comment]
It has me thinking. Their might actually be an easier way for people with rooted devices who use titanium backup. If you had a backup from titanium, without data, wouldn't restoring the save file put everything where it needs to go with less hassle? 
Id love to try it on my RCA tablet, but at the moment, its one of the few android devices over a year old that so far as I can see, has no way of getting rooted. At least the articles I read of people trying ended up bricking their own tablets.

**Comment by robot9706** [comment]
I think titanium wouldn't save you any hassle, because you'd still need to update the APK and the OBB somehow.

**Comment by Xanthor** [comment]
OBB is the data right? Lets say I make a save once I have everything working except for the OBB data using titanium. A user can download that save and restore it with titanium without having to bother to look where it goes then with their own titanium backup of their data they can do a restore and again not have to worry of manually looking to where it goes as titanium backup puts it where its supposed to go. 
A lot of rooted devices are done by people or their friends who may be to worried of messing their game or more up. I figure if I made it this easy, more of the non tech savvy would give it a try.

**Comment by robot9706** [comment]
Yes OBB is the data.

Well Titanium can take care of the saves, but in this case you don't need root, because the vaults are stored on the "external" storage (It's not really external but android likes to call it like that). So basically every app can access the vault files.
