### ISSUE TITLE
Editing dwellers & Exception

### ISSUE THREAD

**Issue by jfgagnon328** [robot9706/FSSE#118]
When I click on "Show Relations", an error dialog is shown (about an exception).

I would also like to be able to edit the ascendants, since the file contains errors (Like -13 for an ascendant, or two fathers as parents).

(I know that ID are reused when dwellers die).

[Vault1.zip](https://github.com/robot9706/FSSE/files/1056008/Vault1.zip)

![foshelter3](https://user-images.githubusercontent.com/29232154/26844707-5095e430-4ac2-11e7-88ca-011b32ad2a2a.PNG)

**Comment by robot9706** [comment]
I found and fixed the problem thanks for the download.

I'll see what I can do about the editing part, however originally I wanted to just show the relations in a tree like form, but the way relationships work in a Vault it's not really possible...

**Comment by jfgagnon328** [comment]
Because the tree would be complicated (lots of disconnected people), or because the data is not reliable?

**Comment by robot9706** [comment]
Because the tree is too complicated and it's not an actual tree. Dwellers can have more than one partner so it's not a basic family tree.

**Comment by jfgagnon328** [comment]
Thank you for the answers, your software is great, the interface is good!  Have a nice day!

**Comment by robot9706** [comment]
I'm not sure about the interface part but thanks :)
