### ISSUE TITLE
Vault layout editor / planner

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#12]
Might apperar earlier in the PC version because it's easier to implement it in Windows Forms than Android UI.

**Comment by fayescarlet64** [comment]
Having mega vaults would be a dream come true. I hope I can contribute somehow now that I've learned how to look at .dll files.

**Comment by Vic2077** [comment]
Hey! How's the work going on this direction? Will it be implemented soon, or not quite so?
Right now i'm experimenting with a big "dweller generator","honeycomb" type Vault, mostly consisting of  single radio rooms, separated with elevators, (as much of them as possible to keep 2 dwellers in each, having 199 Dwellers in total, and i'm noq quite sure on how should i arrange the bottom levels (i want to make enough double or triple Barracks in the middle (probably) and occupy the rest of the free space with max size Warehouses,and keep it symmetrical and make two elevator shafts, connected with teh upper "honeycomb" levels, though i'm having problems with "synchronizing" the elevators of the bottom and upper parts, and genberal simmetry, so the Layout Editor / Planner would really come in handy right now.
if you are almost done with it, and planning to release it soon, i'll stop working on that Vault for now, and wait for the Editor, to save me alot of work. If it will take alot of time to finish it, i'll continue working on my little "project" manually...

**Comment by robot9706** [comment]
It's not in a usable state, and I have no idea when I'll release it. Also exams are comming so in the past weeks working on FSSE became a lower priority thing to do and it might stay like that for some time. :/

**Comment by Vic2077** [comment]
Oh, i see. No problem, then. ) I'll just try to do it manually, or even delay for now, if it will turn to be too bothersome. "Real life" stuff like Exams is much more important. Good luck with it! ;-)
P.S. I might be getting a normal job soon, so i'll probably also have less time for FoS in the upcoming months, i guess...

**Comment by robot9706** [comment]
Turns out to be more work than I thought. I'm going to close this. I might get back to doing this sometime.

**Comment by robot9706** [comment]
TODO:
- Fix living quarters price calculation - Done
- Auto room merge option - Done
- Do elevator placement like the game does - Done
