### ISSUE TITLE
Remove Mice?

### ISSUE THREAD

**Issue by fayescarlet64** [robot9706/FSSE#120]
Just an odd, random suggestion I had, but you know when a room doesn't have anyone assigned to it, mice appear? Is there any way to make the mice disappear? They creep me out a little, and I hate leaving one dweller in there being useless when they could be exploring or on a quest.

If it is not possible, that is fine. I was just curious.

**Comment by robot9706** [comment]
Yup it's possible with mods and it looks like it's very easy.

The mod will be included in the new modpack once I'm done (with the new modding technique).

[Ref](https://github.com/robot9706/FSSE/blob/gh-pages/Mods/ModPack/ModDisableRats.cs)

**Comment by robot9706** [comment]
If you are interested I could send you a test version of the new modpack for testing. Which also contains this mod.

**Comment by fayescarlet64** [comment]
Sure, I'd love to test it out! :D

**Comment by robot9706** [comment]
Here's the download: 
[FSLoader.zip](https://github.com/robot9706/FSSE/files/1089569/FSLoader.zip)

It contains a readme.txt for further installation steps.

**Comment by fayescarlet64** [comment]
It works like a charm! The other new mods are splendid as well! Truly, your work is amazing!

**Comment by robot9706** [comment]
@fayescarlet64: I'm not sure if every mod is ported correctly, so expect bugs :)
