### ISSUE TITLE
Corrupt save data

### ISSUE THREAD

**Issue by GiddyupButtercup** [robot9706/FSSE#123]
Save data corrupt after using this new version (game can't load save file), I'm just using this to fix my dwellers HP that I forgot to put E+ gear while leveling, its get error message when I'm try edit dweller HP that out exploring wasteland.
![error](https://user-images.githubusercontent.com/29380206/27043850-b84c5020-4fc5-11e7-9afd-65368a49522e.JPG)

**Comment by robot9706** [comment]
Are you sure you are using the latest version? Are you trying to edit questing dwellers or exploring dwellers? Also could you include the "Details" (press the button and include the text).

**Comment by robot9706** [comment]
I think I found and fixed the problem. Could you check if it also works for you?
[Dev.zip](https://github.com/robot9706/FSSE/files/1070842/Dev.zip)

**Comment by X07zero** [comment]
Thank you, I have same problem and the fix works ^^

thank again for your work
