### ISSUE TITLE
Save Corruption in latest version (1.4.2) 

### ISSUE THREAD

**Issue by Neyami** [robot9706/FSSE#124]
I opened up my save and modified the skincolor of a dweller and saved it, like I've done many times with the previous versions. This time the save got corrupted however, crashing the game on the loading screen after pressing Enter Vault ###.

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/123
Same?

If not, could you provide some more information? Mainly I'm interested in what kind of dweller did you edit, an exploring, a questing or a working dweller? Because the bulk editing messed up lots of stuff unfortunately.

**Comment by Neyami** [comment]
Oops didn't see that post ^^;

But no, the game just CTDs, no error message~

It was a level 1 dweller that I had just gotten from the wasteland (via the Broadcast Center), and she was placed in a training room (Strength Center)

**Comment by robot9706** [comment]
In that case. could you upload your vault and the "Fallout Shelter.log" (it's in the same folder as the saves) just after the game crashes?

**Comment by Neyami** [comment]
[Vault1crashy.zip](https://github.com/robot9706/FSSE/files/1074246/Vault1crashy.zip)

**Comment by robot9706** [comment]
I think I managed to fix the vault, however MrHandies might be gone..
I also included a fixed (hopefully) version of the editor, could you try if that fixes the problem?
[Dev.zip](https://github.com/robot9706/FSSE/files/1074264/Dev.zip)

**Comment by Neyami** [comment]
Yeah that did it, no more crashy :D
