### ISSUE TITLE
(Three questions and an issue) Deactivating Bottle and Cappy quest & 664 max HP & See total amount of dwellers & Always-questing dwellers

### ISSUE THREAD

**Issue by Nuquina** [robot9706/FSSE#130]
Hello, first thank you a lot, its a wonderful and very useful work and all worked perfectly, the issue below is most to let you know; it didnt damage anything in my vault. 
If these 4 things are too much in the same entry, let me know and I'll post each in a different entry, or if you dont have the time to reply skip some, thank you anyway.

_The main question,_ 
Will Bottle and Cappy stop visiting the vault if I remove "Nabbed from Nuka-World" from finished quests? I started a new vault just to avoid them because deathclaws came constantly, and now I'm not sure if i should do this quest again (now that I can stop random incidents, thanks to your modpack). If deleting the quest they stop coming, I will finish this quest for sure :)

_The second question,_ 
It is about the amount of life with "SUPER dwellers". It displays 664 automatically when I select SUPER dwellers but it seems like 644 is the max so I dont use 664 but type manually 644 for each dweller, just in case. Should I need to use the mod editor to make it work above 644, or is 664 just fine?

_The last question,_ 
Is there a way to see in FSSE (PC version) how many dwellers are in the vault? I think I checked everything but maybe I missed it. I tryed renaming them by ID (just to check and then closed without saving), but 1 comes next to 11 and 111, or 3 after 29 etc. The mod is perfect anyway if the answer is that I cant, and anyway renaming feature would have spared me a lot of time if i had found FSSE sooner.

_The issue,_ 
This part is most to let you know in case you didnt already. Three of my dwellers are always detected as "questing" by the FSSE, even if I didnt do any quest in a while. 
The only effect is that I cant edit them in FSSE (for example, they dont get healed with "Heal" feature or cant unequip their pet, this only inside FSSE; in the game, stimpacks and the rest work properly). I avoided the issue deleting the dwellers, but then again magically 3 dwellers in the vault were recognized as questing in FSSE (they didnt even go to any quest, only to explore wastelands, just like a 4th dewller, who wasnt tagged as questing).

Thanks again, have a very nice day.

**Comment by robot9706** [comment]
1) I'm not sure how that works, but I think once you finished the quest some kind of flag is set so the game knows that you did it, so it doesn't matter if you remove it or not. But I'm not sure, it might work.

2) 664 works without any problems, however 644 is the max so I mistyped that.

3) Currently there's no way to check how many dwellers you have, but that's a simple thing to add.

4) A few updates ago I added a feature to edit multiple dwellers at the same time and it introduced some problems this might be one of them. So if you could upload you vault so I could check it out, that would be cool.

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/131
https://github.com/robot9706/FSSE/issues/132

**Comment by Nuquina** [comment]
Thank you.
Sure, here is the file.
[Vault2.zip](https://github.com/robot9706/FSSE/files/1116984/Vault2.zip)

The questing dwellers are named 
--...Portera Pala
--...Portero Long
--...Portero Abraham
alphabetically they are the three first ones in the list

**Comment by robot9706** [comment]
[FSSEWin.zip](https://github.com/robot9706/FSSE/files/1117020/FSSEWin.zip)

Does this version work for you?

**Comment by Nuquina** [comment]
Wow yes! It's working perfectly and I can see the count of dwellers, thank you!!
