### ISSUE TITLE
Issue (no icon on pet added with FSSE)

### ISSUE THREAD

**Issue by Nuquina** [robot9706/FSSE#136]
Hello,

I added the pet "Polly" (legendary Macaw with +6 DamageBoost) with FSSE, but in the game it doesnt display any image in the inventory or when I click a dweller to add it. Its slot and name appear, but it has no icon like the other items and pets.

I tryed in two different vaults and this happened in both.

Greetings.

**Comment by robot9706** [comment]
You need to mess around with the items so the game reloads the icons, no idea why it happens.

**Comment by Nuquina** [comment]
Ok, thank you.

**Comment by Nuquina** [comment]
It worked, I opened some pet boxes until it dropped a Macaw and then it loaded the icon, thanks.
