### ISSUE TITLE
Custom Outift Texture mod not working

### ISSUE THREAD

**Issue by Wadever** [robot9706/FSSE#138]
Hi Robo,

I tried using the mod and the game just freezes at the into screen. Is there any other way I can load in custom textures for outfits, e.g. through FSSE or anything?

**Comment by robot9706** [comment]
FSSE is a save editor it's not capable of modding the game.

Which outfit mod are you talking about? Because there's two, the old which is for FS 1.6.2 (or something like that) and the new which is available on dropbox but it's not public yet (but there are some links on the net).

**Comment by Wadever** [comment]
I am using the old one (1.6.2) and Assembly-CSharp.dll is making the game unplayable (stucked at the loading screen).

**Comment by robot9706** [comment]
Obviously it was made for FalloutShelter 1.6.2, so if you aren't using FS 1.6.2 then it just won't work.

The new one has some problems so it's not ready yet.

**Comment by Wadever** [comment]
I see. Is there any way I can have my hands on the new version you spoke of?

**Comment by robot9706** [comment]
I'll build the latest version and upload it in a few minutes.

**Comment by Wadever** [comment]
Thanks a bunch!! Cheers

**Comment by robot9706** [comment]
Here's the mod: https://www.dropbox.com/s/35nxdkuoso4up2e/CustomOutfitMod.zip?dl=1
You will also need the "Mod installer" from here: http://www.nexusmods.com/falloutshelter/mods/2/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Ffalloutshelter%2Fajax%2Fmodfiles%2F%3Fid%3D2&pUp=1
(to install you just need to tell the installer where the game is located and which mod you want to install, it's very straightforward)

A guide to use the mod is included in the zip. An example outfit is also included.
