### ISSUE TITLE
Game Crash When Add Pets & Add Legendary Dweller

### ISSUE THREAD

**Issue by YoRHA** [robot9706/FSSE#14]
I have issue,
1) After I add pets to Dweller or Inventory, the pets icon don't show up when I see on Dweller Info and on My Inventory (Storage). This issue sometime make my game crash, or give me silly animation and I can't interact with any room and dweller.
Solution : For now is, get pet with lunchboxes Pet, assign the pet to dweller, then edit pet data.

2) When I add too many Legendary/Rare Dweller, sometime the game crash, and sometime when I sent guy to quest, the one of them become Abraham Washington, then the game crash.
Solution : Just add 1 or 2 Legendary Dweller

**Comment by robot9706** [comment]
Which platform? Version numbers?

**Comment by robot9706** [comment]
Connected to: https://github.com/robot9706/FSSE/issues/23

Fixed.

**Comment by YoRHA** [comment]
Thank for Fixing. :)
I will tell you if I found any bugs. :)

**Comment by robot9706** [comment]
It is not released yet. :)

**Comment by YoRHA** [comment]
At least I can thank for you to fixing it.
I will help you with this FSSE if you want, as Bug-Checker or whatever.

**Comment by robot9706** [comment]
The quickfix version (v1.3.1) is now released.

**Comment by YoRHA** [comment]
Where I can download?
On your web (your github[dot]io) is version 1.3.

**Comment by robot9706** [comment]
I didn't add the build number to the version on the site that's why it's 1.3 not 1.3.1, but if you download it that's 1.3.1 or if you press the "Check for updates" button in the editor it will tell you that the version on the site is 1.3.1.

**Comment by YoRHA** [comment]
OK, thank you. :)
