### ISSUE TITLE
adding a pet in storage from FSSE result in no picture in game

### ISSUE THREAD

**Issue by whismerhill** [robot9706/FSSE#140]
adding a pet in storage from FSSE results in no picture in game
steam version
OS : win7 x64

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/136

**Comment by whismerhill** [comment]
ok sorry

**Comment by whismerhill** [comment]
@robot9706 on 2nd thought I think you could add a warning to the additem button, showing that sometimes icons will not load correctly but that it should solve on messing around with items.

Since it's my belief that a standard user shouldn't have to browse github issues to know about it. Particularly since closed issues require extra manipulations to show
