### ISSUE TITLE
How do I use CSV's to edit game statistics. 

### ISSUE THREAD

**Issue by Jeremiahj17** [robot9706/FSSE#146]
I downloaded the game data CSV's for PC (Steam), and I understand how to view and change the data, but I can't figure out how or where to import it into my game. I looked all over the internet to try to understand it, but all I can find is programs that change the file extension to something else, and there doesn't seem to be any information for using this feature on the download website or elsewhere. Please tell me what file extension to use for Fallout Shelter, and where to put the files.

**Comment by robot9706** [comment]
You can't import data into the game. Those CSVs contain all the items and stuff which is included in the game to use them in Excel (or any spreadsheet software) to create statistics or whatever you want.

EDIT: However there's is an experimental mod which lets you change outfit stats and create custom outfits. It's here: https://www.nexusmods.com/falloutshelter/mods/11/?

**Comment by Jeremiahj17** [comment]
Then how do I add Legendary and/or Rare dwellers to my vault?

**Comment by Jeremiahj17** [comment]
Or modify inventory

**Comment by robot9706** [comment]
Using the save editor: http://robot9706.github.io/FSSE/

**Comment by Jeremiahj17** [comment]
Oh, okay. Sorry, I followed the link to nexus mods, and thought the modpack was all there was to it.

**Comment by Jeremiahj17** [comment]
Thanks for the help

**Comment by robot9706** [comment]
No problem :)
