### ISSUE TITLE
Can FSSE be made to remove the vault size restriction?

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#147]
Started playing this game again and it occurred to me that I could not build any further due to restriction put in. Is there a way to remove that restriction so you can continue building downward?

**Comment by robot9706** [comment]
Vault size limits are kind of hardcoded into the vault graphics and models so it's hard to do anything about that. But I'm not really sure what limitation you are talking about, the vault got smaller or something? I don't follow the game updates that much.
