### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by PRIC3L3SS** [robot9706/FSSE#148]
I'm curious, how do I use them? When I tried creating a weapon I made the id 1 and damage 10000 - 100000. It did not work after this and I am not sure how to successfully make a weapon, outfit, etc.

**Comment by robot9706** [comment]
I think you misunderstood what that feature does (or the name is misleading). It allows users to add items to the database of the editor, those items aren't gonna appear in the game.

It's useful if some items are missing after a game update or if you want to add your custom outfits to the editor which you've made with my custom outfits mod. More info on that here: https://www.nexusmods.com/falloutshelter/mods/11/?
