### ISSUE TITLE
Screen layout fail

### ISSUE THREAD

**Issue by SlimNoble** [robot9706/FSSE#149]
People,
Great utility, Saves me a lot of hassle. Sadly, the size of some bits doesn't work... See the attached screenie!

Cheers

Slim
![fsse screen trouble](https://user-images.githubusercontent.com/33765352/32969222-292ef4b8-cbdc-11e7-9814-6c1682d63730.png)

**Comment by robot9706** [comment]
Released a quickfix, v1.5.7.
It should work properly from now.

(Note: Give some time for the servers to cache the new download)
