### ISSUE TITLE
Lunchboxes Bugged

### ISSUE THREAD

**Issue by lordraz0r** [robot9706/FSSE#150]
Lunchboxes all give 0 Nuka Cola Quantums and nothing else. Editor also corrupts your save often.

**Comment by robot9706** [comment]
Which lunchboxes are you talking about? Lunchboxes which only contain quantum will only give 0 quantum because (as far as I know) it's not possible to change it using save editing.

What did you edit to corrupt the save? Can you give details to replicate tht issue?

**Comment by lordraz0r** [comment]
Normal lunchboxes. When I add some in it adds only these "corrupt" lunchboxes.

**Comment by robot9706** [comment]
Interesting. I quickly tested it using the latest BethNet version with the latest editor. I added 5 simple lunchboxes and got 3 quantum from one of them, but I didn't get any 0 quantums.

Could you attach your save file?

**Comment by prax07** [comment]
I also have the issue with added lunchboxes. Only one single nuka cola card comes out of them. Had an old vault save file I got from I don't know where that adds in 1000 lunchboxes, and that works fine, but added in from the save editor and it breaks every lunchbox. The other additional stuff works fine, pet crates, starter boxes, etc all work fine, it's just the lunchboxes.
