### ISSUE TITLE
Loading Save file

### ISSUE THREAD

**Issue by zScoped** [robot9706/FSSE#156]
Hey Overseer!

So the issue is that every SECOND time i inject the save file it keeps showing the error that file is to big or to small for int 32" something like that but can you please help me how to fix this problem!

I am playing at the official launcher Bethsda

Thank you!

**Comment by robot9706** [comment]
Your save file might be corrupted or something. Could you attach it here in a post?

**Comment by zScoped** [comment]
Oh I fixed it!

**Comment by MisfitRanch101** [comment]
> Oh I fixed it!

how did you fix it?
