### ISSUE TITLE
Can't open save file: data length not valid

### ISSUE THREAD

**Issue by SapeiMarco** [robot9706/FSSE#157]
[Vault1.zip](https://github.com/robot9706/FSSE/files/1824566/Vault1.zip)

FSSE can't open the save file, reason: "Length of data to decrypt is not valid", but the file loads correctly on Android application (Fallout Shelter).

**Comment by robot9706** [comment]
Unfortunatelly it looks like this save file is corrupted, basically it's not possible to read it after a point.

I tried to load it up in game to see if it does anything, but the vault doesn't even show up.

However it looks like the vault is intact, only some kind of quest part got corrupted, by removing that I can load the save in both the game and the editor.

So if you have a more recent version of your vault, I can probably fix it, and then you'll be able to use it in editors.
