### ISSUE TITLE
Padding not correct (Switch)

### ISSUE THREAD

**Issue by callmechknnugz** [robot9706/FSSE#160]
"padding is invalid and cannot be removed" is the error i get when trying to use my switch save.

**Comment by robot9706** [comment]
That could mean a lot of things. For example the save could be corrupted or it's a different format. Could you attach your save file?

**Comment by callmechknnugz** [comment]
[Vault1.zip](https://github.com/robot9706/FSSE/files/2092278/Vault1.zip)

The save file loads perfectly

**Comment by robot9706** [comment]
I checked the save, it's not corrupted however it's not a complete save. The file you attached is only about 2/3 of the actual file. The padding error means the last block of the file is missing, which is (in this case) correct. Are you sure the file transfer method you use is correct? The file is exactly 64KB which is also odd.

**Comment by callmechknnugz** [comment]
I’m using Checkpoint home brew app, but I’ve also used all available applications to do so. 

The backups always come with a Immortal.sav and a Vault1.sav.bkg along side the Vault1 save, I’m unsure if those are the same for the pc or steam versions of the game. 
I can import the entire folder if you would like? Or make a video of sorts and show you. 
The basic process is ‘backup’ to the sdcard, put the sdcard into the computer and upload the file to edit the save

**Comment by robot9706** [comment]
I don't have a switch and I have no idea how it works, so I can't help you with that part.

You mentioned you have .bkp files, those should be backups, see if those are bigger in size, then try to edit them if possible.

**Comment by callmechknnugz** [comment]
I will try that and get back to you! Thank you for your help in the mean time

**Comment by callmechknnugz** [comment]
Reinstalled the extraction application completely and it has worked.
Unsure what went wrong with it. thank you for your help and patience.
