### ISSUE TITLE
Add Nuka Colas Bugged

### ISSUE THREAD

**Issue by DarkFang1994** [robot9706/FSSE#161]
I go to "Edit Lunchboxes" and add Nuka cola quantum. when in game it gives me the boxes for the amount I added but they all contain a card saying x0 and no quantum is given.

**Comment by robot9706** [comment]
I thought I removed that, since edited Nuka boxes are always empty, only bought ones have content. So there's no point adding them (also you can give yourself Nuka Cola Quantums, no need for the lunchbox).
