### ISSUE TITLE
Custom Items [PC/Steam]

### ISSUE THREAD

**Issue by BrennanG05** [robot9706/FSSE#163]
When I make custom items and put them in the storage, I can't find them in the storage when I'm in-game.

**Comment by robot9706** [comment]
In the "Custom items" menu you can add custom item IDs to the item database of the editor, it doesn't add new items to the game itself. You need a mod to do that.

**Comment by BrennanG05** [comment]
What is the mod that I need?

**Comment by robot9706** [comment]
I don't know if there's a general mod for custom items.

I have one which gives modders the ability to create custom outfits, but it's not made for end users.
Here's the link if you are interested: https://www.nexusmods.com/falloutshelter/mods/11
