### ISSUE TITLE
Missing "deserializeID" on a couple of elevators

### ISSUE THREAD

**Issue by Bug64** [robot9706/FSSE#166]
While working on my vault layout, the last two rooms I added (using the Windows version of the editor) were elevators but for some reason they were missing their "deserializeID" field.  The game didn't seem to mind and it added the missing IDs on save.  I only noticed because I had exported the JSON for use in another program.  Here's an example elevator:

      {
        "emergencyDone": false,
        "type": "Elevator",
        "class": "Utility",
        "mergeLevel": 1,
        "row": 4,
        "col": 9,
        "power": true,
        "roomHealth": {
          "damageValue": 0,
          "initialValue": 0
        },
        "mrHandyList": [],
        "rushTask": -1,
        "level": 1,
        "dwellers": [],
        "deadDwellers": [],
        "assignedDecoration": "",
        "roomVisibility": false,
        "roomOutline": false,
        "broken": false
      },

**Comment by robot9706** [comment]
I think I left that field out because I didn't know what values I should put there and the game doesn't really care. But I'll check it out since it was a long time ago.
