### ISSUE TITLE
value was either too large or too small for a int32

### ISSUE THREAD

**Issue by nyokoko** [robot9706/FSSE#169]
hey so i edited my save first time, everything was fine and it loaded alright.
i went to edit it again and it gave me this error. i started a new save, edited it, placed in the 4 basic rooms and tried to re open it and same error. 

[idk how this works very well, sorry but heres a dl for one of the saves](http://www.mediafire.com/file/d4vxw8dk7kxsr35/Vault2.sav/file) if i overedited or something, i apologise in advance for the waste of time

**Comment by robot9706** [comment]
It looks like you edited more caps (or something) than it is possible to store in a 32bit number.

Looking at the raw save file I think this is the problem:
```
resources": {
        "Nuka": 2147481000.0,
        "Food": 2147484000.0,
        "Energy": 2147484000.0,
        "Water": 2147484000.0,
        "StimPack": 2147484000.0,
        "RadAway": 2147484000.0,
        "Lunchbox": 0.0,
        "MrHandy": 0.0,
        "PetCarrier": 0.0,
        "CraftedOutfit": 0.0,
        "CraftedWeapon": 0.0,
        "NukaColaQuantum": 2147484000.0,
        "CraftedTheme": 0.0
 },
```

Maybe try editing max 1mil resources?
