### ISSUE TITLE
Customisable inventory clear.

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#19]
Select which rarity and type (outfit, weapon, recipe, etc.) of items should be removed.
(Also it could be combined, for example: Rare recipes, legendary outfits, etc.)

Could be applied to the vault storage too.

**Comment by fayescarlet64** [comment]
Would expanding Vault storage be viable here, too? Cuz honestly, the size a 3-tier storage room is, it should surely hold more than 100 or so items in there.

**Comment by robot9706** [comment]
Yeah, but that's modding which does not releate to this issue.
