### ISSUE TITLE
Remove caps limit.

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#25]

**Comment by fayescarlet64** [comment]
That would be awesome indeed!

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/blob/gh-pages/Mods/remove_storage_cap.patch

**Comment by robot9706** [comment]
[Patch](https://github.com/robot9706/FSSE/blob/gh-pages/Mods/remove_storage_cap.patch)
