### ISSUE TITLE
Option to change dweller helmet (like the barbershop does)

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#31]

**Comment by fayescarlet64** [comment]
Once I finish my sprite edits, maybe we can pave the way for full unisex outfits like Fallout 4 does, like a man in a dress or a woman in a football uniform. It hasn't been easy, but do you think that could be something viable for modding?

**Comment by robot9706** [comment]
FS outfits need textures for both sexes so if an outfit is made for both they it is possible, but using the same texture on different sexes it not, the layout of them is just too different.

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/63
