### ISSUE TITLE
Bulk editing dwellers.

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#32]

**Comment by fayescarlet64** [comment]
I'm on board with this.

**Comment by Random8669** [comment]
Would be nice to max out all their healths.

BTW, if I wanted to de-level somebody, does it cause issues if I don't set their level 1 HP at 105, set their XP at zero, etc?

Also noticed I have level 50 characters who show zero XP. Does that mean they were leveled up inside the vault? That doesn't make sense either, but it's the only reason I could think of.

**Comment by robot9706** [comment]
Yeah a max hp all could come handy.

The XP and health relation isn't too tight so basically you can edit whatever you want, they only matter when a dweller levels up, because the calculation of the max hp will be wrong if you mess with the level, but other than that deleveing a dweller shouldn't cause problems.

As for the 50lvl 0xp, I'm not really sure about that, but a maybe the game just stops tracking xp when a dweller is maxed (xp is no longer useful which is logical).

**Comment by robot9706** [comment]
Windows: Select dwellers (CTRL/SHIFT), right click and "Edit".
Android: Select dwellers (using the checkboxes), "Menu" and "Edit selected".
