### ISSUE TITLE
Figure out how Quantum Lunchboxes work.

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#37]

**Comment by marsjaninzmarsa** [comment]
Quantum Lunchboxes?

**Comment by robot9706** [comment]
Quantum packs or what, those which you buy to get quantums.

**Comment by robot9706** [comment]
Save does not contain any info about quantums in pack.

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/54
