### ISSUE TITLE
CSV include dweller parents.

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#55]

**Comment by sugnaangus** [comment]
How did you add the "remove family tree" button? Maybe it's something to do with that?

**Comment by robot9706** [comment]
The remove buttons just clears relation lists. But I can reverse search the child dweller ID in other relation lists of dwellers and if I find something that means I found a parent. So I got the method I just need to implement it sometime :)

**Comment by sugnaangus** [comment]
Is there a way to view the current relation lists with the app?

**Comment by robot9706** [comment]
The PC version can show some relation info in the dwellers tab (bottom left button).
