### ISSUE TITLE
Remove party limit of 3 for doing missions

### ISSUE THREAD

**Issue by Sha-Gojyo** [robot9706/FSSE#56]
At this time, it is only possible to do 3 missions at once.
Can this limit be removes the same as with exploring wasteland?

**Comment by robot9706** [comment]
I guess it is possible.

**Comment by robot9706** [comment]
Modded binaries will be released when I'm done with other modding stuff.

Reference: https://github.com/robot9706/FSSE/blob/gh-pages/Mods/remove_quest_team_limit.patch
