### ISSUE TITLE
Fixing There are to many dwellers Waiting in line. bug

### ISSUE THREAD

**Issue by OneTimeFan** [robot9706/FSSE#58]
Being able to delete the extra Vault Dweller that the other vault dweller picked up during a quest in the wasteland.

**Comment by robot9706** [comment]
Why is that a bug?

**Comment by OneTimeFan** [comment]
Once there so many dwellers in line say 10 you can no longer open lunchboxes all you get is "There are to many dwellers waiting in line". Well that goes for the same if you have 10 dwellers in line outside and each one is carrying a extra dweller you can not collect that original dweller until the line is under the 10 limit to allow the new dweller to show up. I was hoping Bethesda would have fix this by now but talking to there support help was like talking to a wall.

**Comment by robot9706** [comment]
So a dweller in the line can't be collected until the dweller it brought back isn't in the line too?

Okay that's a bug, but it's kind of complex to fix it using modding, so I can't do much about that.

**Comment by OneTimeFan** [comment]
I tried on the pc to delete 7 of the 16 dwellers so I can collect the 3 teams of 3 and then I was just going to add the deleted dwellers back. but once I get to deleting the 7th dweller I get 'System.OutOfMemoryException' was thrown. any idea

**Comment by robot9706** [comment]
Without the save, no idea.

**Comment by OneTimeFan** [comment]
Thanks for your time.

**Comment by robot9706** [comment]
If you upload your save I can take a look if you want.

**Comment by OneTimeFan** [comment]
[FS.zip](https://github.com/robot9706/FSSE/files/602311/FS.zip)

**Comment by robot9706** [comment]
Are you sure you are using the latest editor? I can easily edit all of them without any problems, and the game loads the save too.

**Comment by OneTimeFan** [comment]
I'm using 1.3.4

**Comment by OneTimeFan** [comment]
Its just when I get to the 7th dweller I want to delete that error pops up

**Comment by OneTimeFan** [comment]
## How to Remove Random Picked Up Dwellers from Dwellers in Vault Line

Follow the path:
"vault" : "wasteland" : "teams" : "teamEquipment" : "dwellers"

in the JSON file

then remove any dwellers found in each returning dweller's "teamEquipment" leaving only an empty array for "dwellers".

I think it would be a really helpful addition if you could add a button that you would press and it would remove all of the extra random picked up dwellers from all of the dwellers waiting in line. This would fix a very serious game breaking bug and help a lot of people.

**Comment by robot9706** [comment]
Okay that's possible. I was thinking about finding where the picked up dwellers are stored to remove them, but I wasn't sure if that would help or not, because in this case you'll lose them. But if that's fine, then okay.

https://github.com/robot9706/FSSE/issues/59
