### ISSUE TITLE
Add "Unlock all entries in VDSG" to Win version.

### ISSUE THREAD

**Issue by Vic2077** [robot9706/FSSE#62]
I always forget to ask you to add "Unlock all entries in the Vault Dweller's Survival Guide" option in FSSE version for Windows, as it is in the Android version now, so i'll post it here, until i forget about it again... ^__^"

P.S. Sorry, i don't know how to add Labels to Issues yet... .__.;

**Comment by robot9706** [comment]
No prob I added the labels and I'll see when I can get to work on this:)
