### ISSUE TITLE
The outfit changing isn't functioning.

### ISSUE THREAD

**Issue by thewalkingcamel** [robot9706/FSSE#64]
Editor version:v1.5.4,game version:1.9.I tried to change the color of dwellers' outfits for numerous times but it never worked.

**Comment by robot9706** [comment]
Hm maybe not all outfits support changing colors?
I haven't tested this function for ages, so I'm not even sure if the game still supports changing outfit colors.

EDIT: No matter what the game changes the outfit colors back to white. I guess it is hardcoded into the game.

I'm going to leave this ticket open, so I'll know that I have to investigate this.

**Comment by thewalkingcamel** [comment]
@robot9706 The thing is,this function can't even work on outfits like accountant outfits,while survivors in colorful ones can be seen outside your vault.The same thing happens on spring casualwears,motorcycle jackets,etc.

**Comment by thewalkingcamel** [comment]
@robot9706 And,the game doesn't change the outfit colors back to white,it change them back to the original,specific colors of the outfits,according to the editor.

**Comment by robot9706** [comment]
Okay so every outfit has a predefined color and it can't be changed, so this function of the editor is currently useless, but I guess a game modification could help.

**Comment by thewalkingcamel** [comment]
@robot9706 OK But I still have one question:what about those survivors/dwellers that appears in a same kind of outfit with various colors?Why are their outfits...

**Comment by thewalkingcamel** [comment]
@robot9706 Got it.Those colorful outfits are actually not colorful spring casualwears or accountant outfits or anything else,they belong to a series of technical outfits called "casual",that is,those "white shirts" you'll see upon checking the attributes of waiting outsiders.Thanks man.
