### ISSUE TITLE
Quest keeps repeating

### ISSUE THREAD

**Issue by Random8669** [robot9706/FSSE#65]
There's an open issue where a quest (Honeymoon Horror) continuously repeats. I'm guessing it's a matter of the quest not flagging as completed.

https://beta-community.bethesda.net/topic/10667/repeated-quest-all-over-again
https://www.reddit.com/r/foshelter/comments/5gupi3/honeymoon_horror_quest/

Can a fix be added to the save editor? Or would you just prefer to wait and see if Bethesda patches it?

**Comment by robot9706** [comment]
Currently it is only possible to mark completed quests as non completed, so you could do them again.
But I think the reverse could be possible too.

https://github.com/robot9706/FSSE/issues/66

**Comment by robot9706** [comment]
I released a new update. Hopefully everything works :)

So now both editors can mark quests as completed  (+some smaller features) which should fix your issue.
