### ISSUE TITLE
Mark quests as completed

### ISSUE THREAD

**Issue by robot9706** [robot9706/FSSE#66]
Option to mark any quest as completed.

**Comment by Random8669** [comment]
Unfortunately it doesn't fix the issue with Honeymoon Horror. Guess it's more than just an issue marking the quest completed (it actually IS flagged completed, yet still shows up in my quest list).

But I love the new layout for quest data! A lot more descriptive.

**Comment by robot9706** [comment]
The quest stuck in the list might come from somewhere else, because (I don't remember correctly) I think there is a separate list which contains quests shown in the Overseers office UI, but I don't know why marking a quest complete does not remove it from the available quests list.

I think I could make the list a little bit wider because some quest names are too long,, also I should mark chain quests (because for example there are 4 quests called "Anybody home?", but they have different IDs, that's why I decided to show the ID..).
