### ISSUE TITLE
Recipes Bug on PC

### ISSUE THREAD

**Issue by canoekovski** [robot9706/FSSE#67]
I discovered a bug on recipes for PC save editor.

This is my problem, I have institute rifle recipe and plasma rifle found on wasteland so I use FSSE to unlock remaining recipes for both like "amplified" one. But when I'm unlock those recipes on FSSE it did not appears in game. When I unlock all variants Institue Rifle, all Plasma Rifle variants gone in game and vice versa.

**Comment by robot9706** [comment]
Oh well it's a cringy issue. I only add the recipes back to the vault which are in the list, and if you filter them not all of the recipes are present *facepalm*.

1.3.8 will be released today (hopefully) which should fix this issue.
