### ISSUE TITLE
Unlimited Storage not working?

### ISSUE THREAD

**Issue by OriginalImogen** [robot9706/FSSE#71]
I'm using the nodded package on with FSSE, all other mods are currently working from what I've seen, however the Unlimited Storage doesn't seem to be functioning properly. I've made sure to install everything correctly and have it checked on the mods list. Is this something you know of yet? Or did I do something wrong?

**Comment by robot9706** [comment]
Yeah some other users on Nexus also reported this issue, no idea why it happens though. Maybe if you could post your Vault here as an attachment I could take a look.

**Comment by JhonnatanV** [comment]
the Unlimited Storage dont work for me neither here is the link to my vault https://mega.nz/#!J5pmXIgA!5S2_APVVlcLrWxyYkLqNgXnp-ecPOo8r3YCGtgP2A9A

**Comment by robot9706** [comment]
Thanks for the vault, I think I got it figured out!
![pic](https://cloud.githubusercontent.com/assets/3697447/24716286/d90eb73e-1a2e-11e7-91fd-066885936bf5.PNG)

I'll release the new modded binaries after I'm done with other modding stuff.


EDIT: For future reference: https://github.com/robot9706/FSSE/blob/gh-pages/Mods/remove_storage_cap.patch

**Comment by JhonnatanV** [comment]
im sorry but where can i download the patch ? im new here

**Comment by robot9706** [comment]
@JhonnatanV: The modded binaries will be released once I'm done with other modding sutff as I mentioned in my post above.

**Comment by JhonnatanV** [comment]
But what I try to ask is whether it will be a file or an fsse update and from where can i download it when its ready im new here i dont understand anything of this

**Comment by robot9706** [comment]
@JhonnatanV: Mods and the editors (FSSE) are two different things (so it won't be an FSSE update), the files will be available both on the FSSE site (http://robot9706.github.io/FSSE/?s=undw) and on Nexus (http://www.nexusmods.com/falloutshelter/mods/2/?).

**Comment by robot9706** [comment]
@JhonnatanV: The mods are now released, you can access them on the links in my post above.
