### ISSUE TITLE
Windows FSSE update not downloading

### ISSUE THREAD

**Issue by RCRuskin** [robot9706/FSSE#72]
I'm using version 1.3.6 on Windows 10 and get a notice there's an update to 1.3.7 that allows opening Windows 10 save files. I want to update, so click on the button to get the update and it takes me to the landing page http://robot9706.github.io/FSSE/?s=win

Now, when I click on the download link under PC, it opens a new incidence of the landing page http://robot9706.github.io/FSSE/?s=win

At no point do I get a save as prompt or any indication the download happens. I've even checked my downloads folder and nothing is there.

**Comment by robot9706** [comment]
The link takes you to the wrong part of the page, You can find the download link on the top, and that links to "http://robot9706.github.io/FSSE/Download/Win.zip".

EDIT: It's strange it does link to the wrong page on another device I used to check it. It looks like something is cached and the link does not update. I updated the file which contains the link to see if that changes something.

**Comment by RCRuskin** [comment]
Here's the 'top of the page':

FalloutShelter save editor

Easy to use save editor for Fallout Shelter.
Information
FSSE is a FalloutShelter save editor for Android and PC.
It works in BlueStacks and it does not require root.
But the most important thing: it does NOT require any technical skills:
No computer required for the editing process, everything works on your device.
Most of the tools are one click (remove rocks, junk from inventories, etc.).
Vault encrypting and decrypting not required.
No JSON editing required.

Below that is the download link that did not work. For some reason, just now, it did work. Previously, clicking on download took me back to the landing page.
