### ISSUE TITLE
Editor Mods error

### ISSUE THREAD

**Issue by saintmichael95** [robot9706/FSSE#77]
Whenever I click on the mods button at the top of the editor, I receive the error "Failed to load mods config: "value cannot be null. Parameter name: path"" 

I have done everything it said in the directions. I downloaded and moved the two folders to the FalloutShelter_Data folder. I have both the "Managed" and "Mods" folders there and in the mods folder there are "mods_config" and "mods_data". I don't know why it's not working...

**Comment by robot9706** [comment]
Try setting the installation folder of FalloutShelter in the editor settings menu.

**Comment by robot9706** [comment]
From now the error message suggests to browse the FalloutShelter installation folder. That should fix it.
