### ISSUE TITLE
Add an option to spawn raiders.

### ISSUE THREAD

**Issue by zlavitch81** [robot9706/FSSE#95]
Couldn't find out how but i think this part could be connected with it:

```
 {
          "objectiveID": "stop_raider_01",
          "requirements": [
            {
              "requirementID": "stop_raider_01",
              "satisfied": false,
              "currentInvasions": 1
            }
          ],
          "completed": false,
          "incrementLevel": 0
        },
```

Any ideas what i have to write in there to spawn the raiders?

**Comment by zlavitch81** [comment]
BTW great work! 👍

**Comment by robot9706** [comment]
The part you are looking at is an objective (one of the 3). I don't know how to spawn raiders but if you have a raider attack take a look at the "emergencyData" field. That holds what it name says, so it should also contain raider info too.

**Comment by zlavitch81** [comment]
Thanks i'll check it, waiting since an hour for a raider attack... ☕️

**Comment by zlavitch81** [comment]
Got it, had not much time in the last days i guess its this part:

```
"emergencyData": {
      "active": true,
      "cicleTaskId": 43052,
      "mode": 2,
      "raider": {
        "cyclesInRoom": 0,
        "life": 1278.99,
        "level": 0.28,
        "itemCollCount": 0,
        "itemCollCountMax": 1
      },
      "consumedFood": 0,
      "consumedEnergy": 0,
      "consumedWater": 0,
      "emergencyConsumption": "VaultEmergencyConsumption",
      "randomEventTaskId": 1
    },
```

**Comment by zlavitch81** [comment]
It worked - just change the objective counter to 49 and spawn the raiders with the part above to unlock the achievement ;)
```
 "objectiveID": "stop_raider_01",
          "requirements": [
            {
              "requirementID": "stop_raider_01",
              "satisfied": false,
              "currentInvasions": 49
            }
          ],
```

**Comment by Xanthor** [comment]
Actually, what can be done to temporarily stop the raids? The feature to turn them off in the middle of a raid is nice, but having to exit the game to do this can get a bit annoying. A mod to temporarily shut all raids off would be an awesome addition.

**Comment by robot9706** [comment]
@Xanthor: I think it could be done in a mod, I'll see what I can do about that.

https://github.com/robot9706/FSSE/issues/101

**Comment by Neyami** [comment]
How are you getting these scripts (?) ? :o

**Comment by robot9706** [comment]
@Neyami: Those are not scripts, they are raw JSON data from the sav files. There are many tools online which can decrypt the sav file to reveal the JSON content inside. I also have one to develop the editor, but I think I could add a menu option to the editor to get that data if it's useful for somebody.

**Comment by Neyami** [comment]
oooh, yeah that would be nice! :D

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/122
