### ISSUE TITLE
Add Random Dwellers

### ISSUE THREAD

**Issue by WeekMeem** [robot9706/FSSE#98]
Maybe putting a "Randomize" option in the add new dweller screen to make it faster to add more dwellers

**Comment by Ghostsx** [comment]
Agreed, i've been wanting like this, I maxed out all my dwellers specials by accident and I didn't want to do that, now i'm stuck with them, at first I wanted to remove em all and add 1 by 1 but nince I have to name them all and change their skins, etc its gonna take way to much time, wsh something like would be implemented !
